### ISSUE TITLE
[QAIT] Ezi-Pay> ‘Payment Method’: Application displays 500 error message, Inventory gets down and user receives invoice email from Ezi-Pay when internet connection lost on ‘Processing Payment’ page

### ISSUE THREAD

**Issue by Vishuarora-qait** [Certegy/certegy-ezipay-woocommerce#13]
Pre-requisite:
Admin has configured the ‘Ezi-pay’ for AU region

Steps to reproduce:

1. Launch the site: http://ec2-54-206-100-71.ap-southeast-2.compute.amazonaws.com/
2. Login with existing user 
3. Click on ‘Proceed to Checkout’ button
4. Enter shipping address
5. Select payment method as ‘Ezi-Pay’ and click on ‘Place Order’ button
7. Verify the phone number on ‘Verify Mobile’ screen
8. User is navigated to ‘Confirm Mobile’ screen and verify the verification code
9. Verify that user is navigated to ‘You Details’ section and enter the details
10. Enter credit card detail on ‘Payment Method’ screen and click on ‘Submit’ button
11. Drop the internet connection and verify the result

Actual Result: Application displays 500 error code when internet connection lost on ‘Processing Payment’ page which seems to be correct but inventory gets down and user received invoice email from Ezi-Pay. 

Refer to the screencast <<http://screencast-o-matic.com/watch/cbX6Qz2267 >> for more details

Expected Result: Inventory should not get down and invoice email should not be triggered to the user as 500 error page appears when internet connection lost.

**Comment by Vishuarora-qait** [comment]
We have observed the following:

1. Application displays Error code: 500 when internet connection lost on ‘Processing Payment’ page
2. When user clicks on ‘Return to Cart’ button from 500 error page, user navigates user to the shopping cart page and displays message ‘You have successfully canceled your Certegy Ezi-Pay payment. Please click on ‘Update Shopping Cart’.
3. Inventory gets down 
4. Application displays order status as ‘Canceled’ under ‘My Orders’ 
5. User also received Ezi-Pay invoice on his/her registered email address

**Comment by blueninja2** [comment]
#[QAIT] Ezi-Pay> ‘Payment Method’: Application displays 500 error, inventory gets down and user received invoice email from Ezi-Pay when internet connection lost on ‘Processing Payment’ page

**Comment by sam-flexi** [comment]
Duplicate of [Issue 16](https://github.com/Certegy/certegy-ezipay-magento-2.x/issues/16) on Magento 2.x Ezipay board
