### ISSUE TITLE
[QAIT] Ezipay [WooCommerce]> Inventory is not getting down.

### ISSUE THREAD

**Issue by Vishuarora-qait** [Certegy/certegy-ezipay-woocommerce#3]
**Steps to reproduce:**
1. Launch URL: http://ec2-54-206-100-71.ap-southeast-2.compute.amazonaws.com/
2. Add any product in cart and proceed to checkout using Ezipay.
3. Make payment using ezipay.
4. Verify the result.

**Actual Result:** Inventory is not getting down.

Refer to screencast << https://www.screencast.com/t/rXpYrLIJ  >> for more details.

**Expected Result:** Inventory should be updated after successful payment.

**Comment by sam-flexi** [comment]
Inventory management is working okay in the Oxipay WooCommerce plugin.

**Comment by Certegy** [comment]
This should be fixed as of 197f8dd6ae3936b78e2be5ad786871d93b16919e
