### ISSUE TITLE
[QAIT] WooCoomerce> Card deatils page> Enter CVV number 200> Click on Return to Cart Button> Application displays thankyou message even if payment gets failed.

### ISSUE THREAD

**Issue by Vishuarora-qait** [Certegy/certegy-ezipay-woocommerce#9]
Test Data: This issue is reproducible on following devices:
Safari with iOS 11.1
Chrome 62 with Android 7

Steps to reproduce:

1.Launch the site: http://ec2-54-206-100-71.ap-southeast-2.compute.amazonaws.com/
2.Add products in cart
3.Tap on ‘Proceed to Checkout’ button
4.Enter shipping address
5.Select payment method as ‘Ezi-Pay’ and tap on ‘Proceed to Certegy Eazipay’ button
6.Verify the phone number on ‘Verify Mobile screen
7.Confirm the mobile numbering by entering verification code and tap on ‘Submit’ button
8.Verify that user is directed to ‘Your details screen'
9. Enter all the details and CVV code is 200 then click on proceed Button.
10 Verify that application display Transaction decline screen, here click on return to Cart Button.
Actual Result:Application displays thankyou message even if payment gets failed.
Expected Result: Application does not display the Thanku Message.
Refer to screencast:https://screencast-o-matic.com/watch/cbXQlI2Iek

**Comment by Vishuarora-qait** [comment]
Also, There is no option to complete the transaction once transaction has been declined from Ezi-pay and user has clicked on 'Return to Cart' button from Declined page. Shopping cart also becomes empty

**Comment by Certegy** [comment]
this is intentional and enabled for testing only
